export const FETCH_CHANNELS_ERROR = "FETCH_CHANNELS_ERROR";
export const FETCH_CHANNELS_PENDING = "FETCH_CHANNELS_PENDING";
export const FETCH_CHANNELS_SUCCESS = "FETCH_CHANNELS_SUCCESS";

export const SELECT_CHANNEL = "SELECT_CHANNEL";

export const FETCH_CHANNEL_MESSAGES_PENDING = "FETCH_CHANNEL_MESSAGES_PENDING";
export const FETCH_CHANNEL_MESSAGES_SUCCESS = "FETCH_CHANNEL_MESSAGES_SUCCESS";

export const SAVE_CHANNEL_MESSAGE = "SAVE_CHANNEL_MESSAGE";
